### ISSUE TITLE
Fix gaps in data

### ISSUE THREAD

**Issue by sheldak** [membraneframework/membrane_dashboard#15]
Tested with [Videoroom](https://github.com/membraneframework/membrane_demo/tree/master/webrtc/videoroom). Following gaps appear in the dashboard when live update is enabled:
![Screenshot 2021-06-07 at 12 26 21](https://user-images.githubusercontent.com/25062706/121004231-b754bf00-c78e-11eb-8639-e76d88c8f5d8.png)
After clicking **Search** they disappear.

**Comment by Qizot** [comment]
For now the gaps are not visible as we changed scatter plot to linear one.
