### ISSUE TITLE
Get metrics from query result

### ISSUE THREAD

**Issue by sheldak** [membraneframework/membrane_dashboard#17]
Currently list of metrics is hardcoded in `dashboard_live.ex`. Extracting them from queries during **Search** and **Live update**  and appropriate changing number of charts displayed by uPlot would be a more generic solution.

Additionally, it will be a good idea to have some map `metric => metric_data` sent to frontend instead of just list. This will give us more explicit information which data regards particular metric. Now order of sent metric data must match order of metrics sent in `:charts_init` event.

**Comment by Qizot** [comment]
Done with #31
